name: PHP Pipeline
on: [push, pull_request]

permissions:
  contents: read
concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        php-versions: ['7.4', '8.0']
        laravel: ['6.*', '7.*', '8.*']
        stability: ['prefer-lowest', 'prefer-stable']
        include:
          - php-versions: '7.4'
            laravel: '6.*'
          - php-versions: '7.4'
            laravel: '7.*'
          - php-versions: '7.4'
            laravel: '8.*'
          - php-versions: '8.0'
            laravel: '6.*'
          - php-versions: '8.0'
            laravel: '7.*'
          - php-versions: '8.0'
            laravel: '8.*'
    name: PHP ${{ matrix.php-versions }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php-versions }}-composer-
            dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php-versions }}-
            dependencies-laravel-${{ matrix.laravel }}-
            dependencies-laravel-
            dependencies-

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      #- name: Run test suite
      #  run: composer run-script test

  # Check the PHP code follow the coding standards
  php-cs-fixer:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Directory
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Validate composer config
        run: composer validate --strict

      - name: Composer Install
        run: COMPOSER_PROCESS_TIMEOUT=600 composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff

  # Run PHPStan against the module and a Laravel release
  phpstan:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: PHP Static Analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
          php: ['7.4', '8.0']
      fail-fast: false
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # will be overriden by platform.php in composer.json see https://phpstan.org/config-reference#phpversion
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml
          coverage: none  # disable coverage to disable xdebug in the action.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer Directory
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Install
        run: |
          COMPOSER_PROCESS_TIMEOUT=600 composer install --ansi --prefer-dist --no-interaction --no-progress
          rm composer.lock
          composer config platform.php ${{ matrix.php }}

      - name: Run phpstan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon.dist

  # Run PHPUnit against the module
  phpunit:
    permissions:
      contents: read  # for actions/checkout to fetch code
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0']
      fail-fast: false

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, gd, xml, dom, json, fileinfo, curl, zip, iconv, simplexml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
      # to be complete with Laravel configuration and setting
